# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Democratizing Data"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL = "https://chezo.uno/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "&copy; Aki Ariga 2017-{year}"

############################
## Advanced options below ##
############################

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = true  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

disableAliases = false
enableRobotsTXT = true
timeout = 600000
summaryLength = 40

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest", "redirects", "headers" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

[imaging]
  resampleFilter = "lanczos"
  quality = 75
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

[markup.goldmark.renderer]
  unsafe = true

[module]
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify-cms"
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify"
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5"

# Workaround Hugo publishing taxonomy URLs as plurals - consistently use singular across Wowchemy.
[permalinks]
  authors = "/author/:slug/"
  tags = "/tags/:slug/"
  categories = "/categories/:slug/"
  publication_types = "/publication-type/:slug/"

[params]
  mainSections = ['post', 'blog']

[markup]
  _merge = "deep"

[security]
  _merge = "deep"

[sitemap]
  _merge = "deep"

[[cascade]]
  share = true
  show_related = true
  reading_time = true
  pager = true
[cascade._target]
  path = "/post/**"

[[cascade]]
  share = true
  show_related = true
  reading_time = true  
  pager = true  
[cascade._target]
  path = "/blog/**"
