title: Democratizing Data
baseURL: https://chezo.uno/
copyright: "&copy; Aki Ariga 2017-{year}"

cascade:
  - share: true
    show_related: true
    reading_time: true
    show_date_updated: true
    pager: true
    _target:
      path: /post/**
      kind: page
  - share: true
    show_related: true
    reading_time: true
    show_date_updated: true
    pager: true
    _target:
      path: /blog/**
      kind: page


build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
defaultContentLanguage: en
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true
pagination.pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _files$
  - _cache$
disableAliases: false
timeout: 600000
summaryLength: 40
outputs:
  home:
    - HTML
    - RSS
    - headers
    - redirects
    - backlinks
  section:
    - HTML
    - RSS
mediaTypes:
  application/manifest+json:
    suffixes:
      - webmanifest
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
permalinks:
  authors: /author/:slug/
  tags: /tags/:slug/
  categories: /categories/:slug/
  publication_types: /publication-type/:slug/
params:
  mainSections:
    - post
    - blog
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep
