main:
  - name: Home
    url: /
    weight: 10
  - name: Blog
    url: /#blogs
    weight: 20
  - name: Blog (Japanese)
    url: /#posts
    weight: 25
  - name: Publications
    url: /#publications
    weight: 40
  - name: Talks
    url: /#talks
    weight: 50
  - name: CV
    url: /aki_ariga_cv.pdf
    weight: 70
