# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

amazonJpAffiliate = "chezou-22"

# Display a logo in navigation bar rather than title (optional).
#   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
logo = ""

############################
## Social
############################

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image = ""

# Show estimated reading time for posts? (true/false)
reading_time = true

# Enable in-built social sharing buttons? (true/false)
sharing = true

# Link authors to their profile page? (true/false)
link_authors = true

# Load JS plugins
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_js  = []

# Show related content at the bottom of pages?
[show_related]
  page = false
  post = true
  project = false
  publication = false
  talk = false

############################
## Marketing
############################

[marketing.seo]
  site_type = "Person"
  local_business_type = ""
  org_name = ""
  description = "Leverage data for your life"
  twitter = "chezou"
  
[marketing.analytics]
  google_analytics = "G-FWV6PBXHBT"
  google_tag_manager = ""


[header.navbar]
  enable = true
  align = "l"
  show_logo = true
  show_language = false
  show_day_night = true
  show_search = true
  highlight_active_link = true

[footer.copyright]
  notice = "&copy; Aki Ariga 2017-{year}"

############################
## Regional Settings
############################
[locale]
# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "2006-01-02"
#   Examples: "3:04 pm" or "15:04"
time_format = "15:04"

# Address format (choose from the [address_formats] list below or add you own to the list).
address_format = "en-us"

############################
## Advanced
############################

[features.repository]
  url = "https://github.com/chezou/chezo.uno"
  content_dir = "content"
  branch = "master"

[features.avatar]
  gravatar = true
  shape = "circle"

# Configuration of publication pages.
[publications]
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"

  # Citation style ("apa" or "mla")
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 2
  publication_view = 2
  talk_view = 2


############################
## Site Features
############################

[features.syntax_highlighter]
  enable = true
  theme_light = "github-light"
  theme_dark = "github-dark"
  extra_languages = ["r", "latex"]  # Add support for highlighting additional languages

# Enable LaTeX math rendering? true/false
#   If false, you can enable math on a per page basis as needed.
[features.math]
  enable = true

[features.privacy_pack]
  enable = true

############################
## Comments
############################
[features.comments]
  # Comment provider:
  #   0: Disabled
  #   1: Disqus (https://disqus.com)
  #   2: Commento (https://commento.io)
  provider = ""

  # Which page types are commentable?
  commentable = {page = true, post = true, docs = true, project = true, publication = true, talk = true}

  # Configuration of Disqus.
  [features.comments.disqus]
    shortname = ""  # Paste the shortname from your Disqus dashboard.
    show_count = true  # Show comment count in page header? (true/false)

############################
## Search
############################
[features.search]
  # Search provider:
  #   0: No search engine
  #   1: Academic (built-in)
  #   2: Algolia (https://www.algolia.com)
  provider = "wowchemy"

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [features.search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = true

############################
## Maps
############################
[features.map]
  provider = ""
  api_key = ""
  zoom = 15


# Content Management System
[extensions.cms]
 # Enable the admin panel. See https://wowchemy.com/docs/install/
 netlify_cms = true
 branch = "master"

[extensions.academicons]
  enable = true

############################
## Theme
############################

[appearance]
  theme_day = "minimal"
  theme_night = "minimal"
  font = "minimal"
  font_size = "L"
