content:
  - name: post
	type: collection
	label: ブログ記事
	path: content/post
	subfolders: true
	filename: index.md
	fields:
	    - { name: title, label: 記事タイトル, type: string, required: true }
	    - { name: featured_image, label: トップ画像, type: image, required: true }
        - { name: subtitle, label: サブタイトル, type: string }
	    - { name: date, label: 日付, type: date, required: true, 
	        options: { time: true, format: yyyy-MM-dd'T'HH:mm:ss'-07:00'} }
	    - { name: body, label: 本文, type: rich-text }
	    - { name: categories, label: カテゴリ, type: string, list: true }
	    - { name: tags, label: タグ, type: string, list: true }
	    - { name: draft, label: 下書き, type: boolean, default: true }
        - { name: featured, label: feature, type: boolean, default: false }
