settings:
  content:
    merge: true

media:
  - name: shared_media
    input: assets/media
    output: media
    categories: [image]
  - name: post_media
    input: content/post
    output: post
    categories: [image]
  - name: blog_media
    input: content/blog
    output: blog
    categories: [image]

  
content:
  - name: post
    type: collection
    label: ブログ記事
    path: content/post
    subfolders: true
    filename: index.md
    delimiters: ["---\n", "---\n"]
    exclude: ["_index.md"]
    view:
      layout: tree
      node:
        filename: index.md
        hideDirs: all
    fields:
    - { name: title, label: 記事タイトル, type: string, required: true }
    - { name: subtitle, label: サブタイトル, type: string }
    - { name: date, label: 日付, type: date, required: true, options: { time: true, format: yyyy-MM-dd HH:mm:ssxxx } }
    - { name: lastmod, label: 更新, type: date, options: { time: true, format: yyyy-MM-dd HH:mm:ssxxx } }
    - { name: body, label: 本文, type: rich-text }
    - { name: categories, label: カテゴリ, type: string, list: true }
    # - { name: keywords, label: キーワード, type: string, list: true }
    # - { name: recommendations, label: レコメンド, type: string, list: true }
    - { name: tags, label: タグ, type: string, list: true }
    - { name: draft, label: 下書き, type: boolean, default: true }
    - { name: featured, label: feature, type: boolean, default: false }
    - name: image
      label: 画像
      type: object
      fields:
      - name: placement
        label: placement
        type: number
      - name: caption
        label: caption
        type: string
      - name: focul_point
        label: focul point
        type: string
      - name: preview_only
        label: preview only
        type: boolean
        default: false
      - name: filename
        label: image path
        type: image
        options:
          path: post_media
  - name: blog
    type: collection
    label: blog post
    path: content/blog
    subfolders: true
    filename: index.md
    delimiters: ["---\n", "---\n"]
    exclude: ["_index.md"]
    fields:
    - { name: title, label: 記事タイトル, type: string, required: true }
    - { name: subtitle, label: サブタイトル, type: string }
    - { name: date, label: 日付, type: date, required: true, options: { time: true, format: yyyy-MM-dd HH:mm:ssxxx } }
    - { name: lastmod, label: 更新, type: date, options: { time: true, format: yyyy-MM-dd HH:mm:ssxxx } }
    - { name: body, label: 本文, type: rich-text }
    - { name: categories, label: カテゴリ, type: string, list: true }
    # - { name: keywords, label: キーワード, type: string, list: true }
    # - { name: recommendations, label: レコメンド, type: string, list: true }
    - { name: tags, label: タグ, type: string, list: true }
    - { name: draft, label: 下書き, type: boolean, default: true }
    - { name: featured, label: feature, type: boolean, default: false }
    - name: image
      label: 画像
      type: object
      fields:
      - name: caption
        label: caption
        type: string
      - name: focul_point
        label: focul point
        type: string
      - name: preview_only
        label: preview only
        type: boolean
        default: false
