name: Trigger Netlify Build
on:
  schedule:
    - cron: '5 0-23/6 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5dfd7d85738b6d795071053e
