name: Post process by prelims

on:
  push:
    paths:
      - 'content/blog/**'
      - 'content/post/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout Repo
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v9

      - name: cache HuggingFace models
        uses: actions/cache@v6
        with:
          path: ~/.cache/huggingface
          key: hf-${{ hashFiles('.github/workflows/prelims-cli.yml') }}
          restore-keys: hf-

      - name: execute prelims-cli
        run: uvx --python 3.13 'prelims-cli[embedding]' --config ./scripts/config/embedding.yaml

      - name: commit files
        run: |
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add content .prelims_embedding_cache_en.db .prelims_embedding_cache_ja.db
            git commit -m "Updated by GitHub Actions"
            git push
          fi

